version: '3.7'

services:
  back:
    build: backend
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env.prod
  # front:
  #   build: 
  #     context: frontend
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env.prod
  db:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
volumes:
  postgres_data:
